# Generated by Django 4.0 on 2022-03-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('number', models.IntegerField(max_length=20, verbose_name='Numero')),
                ('Correo', models.EmailField(max_length=500, unique=True, verbose_name='Correo')),
                ('Direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('pregunta', models.CharField(max_length=500, verbose_name='pregunta')),
                ('pregunta1', models.CharField(max_length=500, verbose_name='pregunta')),
                ('pregunta2', models.CharField(max_length=500, verbose_name='pregunta')),
                ('pregunta3', models.CharField(max_length=500, verbose_name='pregunta')),
                ('pregunta4', models.CharField(max_length=500, verbose_name='pregunta')),
                ('pregunta5', models.CharField(max_length=500, verbose_name='pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
