# Generated by Django 4.0 on 2022-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='pregunta',
            field=models.TextField(max_length=500, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta1',
            field=models.TextField(max_length=500, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta2',
            field=models.TextField(max_length=500, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta3',
            field=models.TextField(max_length=500, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta4',
            field=models.TextField(max_length=500, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta5',
            field=models.TextField(max_length=500, verbose_name='pregunta'),
        ),
    ]
