# Generated by Django 4.0 on 2022-03-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0002_alter_adoption_pregunta_alter_adoption_pregunta1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='Apellidos',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='number',
            field=models.IntegerField(max_length=60, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta',
            field=models.TextField(max_length=100, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta1',
            field=models.TextField(max_length=100, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta2',
            field=models.TextField(max_length=100, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta3',
            field=models.TextField(max_length=100, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta4',
            field=models.TextField(max_length=100, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pregunta5',
            field=models.TextField(max_length=100, verbose_name='pregunta'),
        ),
    ]
