# Generated by Django 4.0 on 2022-03-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0003_alter_adoption_apellidos_alter_adoption_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='pregunta',
            field=models.TextField(max_length=60, verbose_name='pregunta'),
        ),
    ]
