# Generated by Django 4.0 on 2022-03-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0004_alter_adoption_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
