# Generated by Django 4.0 on 2022-03-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='image2',
            field=models.ImageField(default='', upload_to='pets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets',
            name='image3',
            field=models.ImageField(default='', upload_to='pets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets',
            name='image4',
            field=models.ImageField(default='', upload_to='pets'),
            preserve_default=False,
        ),
    ]
