# Generated by Django 4.0 on 2022-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pets_image2_pets_image3_pets_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
