# Generated by Django 3.2.6 on 2021-09-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
                'db_table': 'razas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'raza gato',
                'verbose_name_plural': 'razas gatos',
                'db_table': 'raza gatos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.BigIntegerField(verbose_name='Teléfono')),
                ('affair', models.TextField(max_length=500, verbose_name='Asunto')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'contactos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'tipo_documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'raza perro',
                'verbose_name_plural': 'razas perros',
                'db_table': 'raza perros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Mascota')),
                ('pet_age', models.PositiveIntegerField(verbose_name='Edad')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('razas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.breed')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'db_table': 'mascotas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(max_length=500, verbose_name='Descripción')),
                ('question2', models.TextField(max_length=500, verbose_name='Descripción')),
                ('question3', models.TextField(max_length=500, verbose_name='Descripción')),
                ('question4', models.TextField(max_length=500, verbose_name='Descripción')),
                ('question5', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'cuestionario',
                'verbose_name_plural': 'cuestionarios',
                'db_table': 'cuestionario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('document', models.BigIntegerField(verbose_name='No documento')),
                ('Email', models.EmailField(max_length=100, verbose_name='Correo')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('telephone', models.BigIntegerField(verbose_name='Telefono')),
                ('birth_date', models.DateField(max_length=50, verbose_name='Fecha nacimiento')),
                ('direction', models.CharField(max_length=50, verbose_name='Direccion')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.location')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.document')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'registro_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Request_adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='mensaje')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.mascot')),
                ('registrousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.user_register')),
            ],
            options={
                'verbose_name': 'solicitud adopcion',
                'verbose_name_plural': 'solicitudes adopciones',
                'db_table': 'solicitud_adopcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.location')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('registro_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.user_register')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donaciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='raza_gatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.cat'),
        ),
        migrations.AddField(
            model_name='breed',
            name='raza_perros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.dog'),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('solicitud_adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPWebanimal.request_adoption')),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
                'db_table': 'adopcion',
                'ordering': ['id'],
            },
        ),
    ]
