# Generated by Django 3.2.6 on 2021-09-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Mascota')),
                ('pet_age', models.PositiveIntegerField(verbose_name='Edad')),
                ('breed', models.CharField(max_length=100, verbose_name='Raza')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('nuDocument', models.PositiveBigIntegerField(verbose_name='Número de Documento')),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
                'db_table': 'adopcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'tipo_documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'tipo_donacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Mascota')),
                ('pet_age', models.PositiveIntegerField(verbose_name='Edad')),
                ('breed', models.CharField(max_length=100, verbose_name='Raza')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nuDocument', models.IntegerField(verbose_name='No. de Documento')),
                ('location', models.CharField(max_length=40, verbose_name='Localidad')),
                ('Neighborhood', models.CharField(max_length=40, verbose_name='Barrio')),
                ('address', models.CharField(max_length=40, verbose_name='Dirección')),
                ('question', models.TextField(verbose_name='Alguna Pregunta')),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.adopcion')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.pet')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud_adopcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('phone', models.IntegerField(verbose_name='Celular')),
                ('birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('no_document', models.BigIntegerField(verbose_name= 'No. de Documento')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.document')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.donation')),
                ('solicitud_adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.solicitud')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
    ]
