# Generated by Django 4.0 on 2022-03-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
